// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNBbUo2R1cNsAsX5WyemPMjQYG-hEMlcc',
    appId: '1:810870348638:web:d05c27bf30480810870dcf',
    messagingSenderId: '810870348638',
    projectId: 'chesskings-cfcbb',
    authDomain: 'chesskings-cfcbb.firebaseapp.com',
    storageBucket: 'chesskings-cfcbb.appspot.com',
    measurementId: 'G-S2HZ3JFKE3',
    // 👇 المتغيّر الجديد
    databaseURL: 'https://chesskings-cfcbb-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGgDQO1gYOQUK7RfBz51p-8_Gsn1sTC4U',
    appId: '1:810870348638:android:5c50307c70a50149870dcf',
    messagingSenderId: '810870348638',
    projectId: 'chesskings-cfcbb',
    storageBucket: 'chesskings-cfcbb.appspot.com',
    // 👇 المتغيّر الجديد
    databaseURL: 'https://chesskings-cfcbb-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeEqrMMbm_pC9Oap7kxzuaN5G7Gm7_iVk',
    appId: '1:810870348638:ios:a3897cea5ab71f1b870dcf',
    messagingSenderId: '810870348638',
    projectId: 'chesskings-cfcbb',
    storageBucket: 'chesskings-cfcbb.appspot.com',
    androidClientId:
    '810870348638-2c84pgkidigfmd7hqq2k937b473009hu.apps.googleusercontent.com',
    iosClientId:
    '810870348638-6im737uv9prpho4f8ngp64mh26059609.apps.googleusercontent.com',
    iosBundleId: 'com.example.chessKings',
    // 👇 المتغيّر الجديد
    databaseURL: 'https://chesskings-cfcbb-default-rtdb.firebaseio.com',
  );
}
